[workspace]
members = [
    "apps/desktop/src-tauri",
    "crates/magies-core-runtime",
    "crates/magies-domain",
    "crates/magies-platform",
    "crates/magies-profiles",
    "crates/magies-routing",
    "crates/magies-session",
    "crates/magies-storage",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "UNLICENSED"
rust-version = "1.85"
version = "1.0.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
