[package]
name = "magies-core-runtime"
description = "Proxy core process lifecycle"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
magies-platform = { path = "../magies-platform" }
sha2 = "0.10"
thiserror = "2"

[lints]
workspace = true
